version: "3"

services:
    postgre:
        image: postgres:12
        container_name: "POSTGRE-ECOMMERCE"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=docker123
        ports:
            - 5432:5432
        volumes:
            - volume-ecommerce-potgre:/var/lib/postgresql:rw
            - volume-ecommerce-postgre-data:/var/lib/postgresql/data:rw
        networks:
            - network-ecommerce

    pgadmin:
        image: dpage/pgadmin4:4.16
        container_name: "PGADMIN-ECOMMERCE"
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        volumes:
            - volume-ecommerce-pgadmin:/pgadmin4:rw
            - volume-ecommerce-pgadmin-lib:/var/lib/pgadmin:rw
            - volume-ecommerce-pgadmin-certs:/certs:rw
        ports:
            - 80:80
        depends_on:
            - postgre
        networks:
            - network-ecommerce

networks:
    network-ecommerce:
        driver: bridge

volumes:
    volume-ecommerce-potgre:
    volume-ecommerce-postgre-data:
    volume-ecommerce-pgadmin:
    volume-ecommerce-pgadmin-lib:
    volume-ecommerce-pgadmin-certs: